spring:
  application:
    name: babysense_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/babysense_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update # 테이블이 없으면 자동으로 만들어줌
    show-sql: true
    properties:
      hibernate:
        format_sql: true